version: '3.8'
services:
  web:
    build: .
    command: python bookstore/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
    environment:
      - DEBUG=True
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_51KZINkIRFuihjY1FZF1FE3vaB36f7DPYe2ybw64u4E2rmPha6D02jltMcZuUU9eSDP3dUY4a0B4AU6B1MMIs4Lt000i9iByloG
      - STRIPE_TEST_SECRET_KEY=sk_test_51KZINkIRFuihjY1F0sQ9uc8IqaAiUtQoiNZJdC3dptg2LMJv5MHmb19kM653JaXVJvGGE10HFGwN8IYUqX4jcWee005KACPMBz

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=bookstore_keeper
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=bookstore
