# Generated by Django 4.0.2 on 2022-02-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('volume', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('downloads', models.BigIntegerField()),
                ('rate', models.DecimalField(decimal_places=1, max_digits=4)),
                ('published', models.BooleanField(default=True)),
                ('path', models.TextField(blank=True)),
                ('author', models.ManyToManyField(related_name='books_BooksToAuthor', to='books.Authors')),
            ],
        ),
        migrations.AddField(
            model_name='authors',
            name='published_books',
            field=models.ManyToManyField(to='books.Books'),
        ),
    ]
