# Generated by Django 4.0.2 on 2022-02-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_authors_published_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='published_books',
            field=models.ManyToManyField(blank=True, related_query_name='books_AuthorPublished', to='books.Books'),
        ),
    ]
