# Generated by Django 4.0.2 on 2022-02-28 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_alter_authors_published_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='rate',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
        migrations.CreateModel(
            name='Reviews2Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(default='')),
                ('review_rate', models.DecimalField(decimal_places=5, max_digits=7)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
            ],
        ),
    ]
