# Generated by Django 4.0.2 on 2022-02-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_books_rate_alter_reviews2books_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews2books',
            name='review_rate',
            field=models.SmallIntegerField(),
        ),
    ]
