# Generated by Django 4.0.2 on 2022-03-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_reviews2authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='published_books',
            field=models.ManyToManyField(related_query_name='books_AuthorPublished', to='books.Books'),
        ),
    ]
