# Generated by Django 4.0.2 on 2022-03-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_authors_published_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
