# Generated by Django 4.0.3 on 2022-03-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_books_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='published_books',
            field=models.ManyToManyField(blank=True, related_query_name='books_AuthorPublished', to='books.books'),
        ),
        migrations.AlterField(
            model_name='books',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='books_BooksToAuthor', to='books.authors'),
        ),
    ]
