# Generated by Django 4.0.2 on 2022-02-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reviews_sent',
            field=models.BigIntegerField(blank=True),
        ),
    ]
